/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_f7BcQEWjW",
    "aws_user_pools_web_client_id": "5qs041b27t3mmj563k2pkfvi0c",
    "oauth": {
        "domain": "ap-south-1f7bcqewjw.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "profile"
        ],
        "redirectSignIn": "https://d1ixvq6f4z10fe.cloudfront.net,https://localhost:3000",
        "redirectSignOut": "http://localhost:8080,https://d1ixvq6f4z10fe.cloudfront.net",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "GIVEN_NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_content_delivery_bucket": "torefrontend-20250614010336-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "ap-south-1",
    "aws_content_delivery_url": "https://d1ixvq6f4z10fe.cloudfront.net",
    "API": {
        "endpoints": [
            {
                "name": "StoreIT-backend",
                "endpoint": "https://euwtxgs2v1.execute-api.ap-south-1.amazonaws.com/Prod",
                "region": "ap-south-1"
            }
        ]
    }
};


export default awsmobile;
